#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the Bitcoin Cash main and test networks
 * @generated by contrib/seeds/generate-seeds.py
 *
 * Each string must be numeric IPv4 dot-notation or numeric
 * IPv6 hex notation, followed by a colon and a port.
 */
static const SeedSpec6 pnSeed6_main[] = {
    { "85.195.104.232:2137" },
    { "72.230.176.60:2137" },
    { "194.36.145.176:2137" },
    { "199.192.16.55:2137" }
};

static const SeedSpec6 pnSeed6_testnet3[] = {
};

static const SeedSpec6 pnSeed6_testnet4[] = {
};

static const SeedSpec6 pnSeed6_scalenet[] = {
};
#endif // BITCOIN_CHAINPARAMSSEEDS_H
